export const RQ_KEY_USER = "RQ_KEY_USER";
export const RQ_KEY_ORGANIZED_EVENT = "RQ_KEY_ORGANIZED_EVENT";
export const RQ_KEY_EVENT_BY_ID = "RQ_KEY_EVENT_BY_ID";
export const RQ_KEY_GET_ALL_EVENT = "RQ_KEY_GET_ALL_EVENT";
export const RQ_KEY_GET_ALL_USER = "RQ_KEY_GET_ALL_USER";
export const RQ_KEY_GET_ALL_COUNT = "RQ_KEY_GET_ALL_COUNT";
export const RQ_KEY_GET_ALL_REGISTERED_EVENTS =
  "RQ_KEY_GET_ALL_REGISTERED_EVENTS";
